src/etaoin/api.clj

I just noticed this when I was looking at the docs.

Remove fake argument from docstring

---

src/etaoin/api.clj

This command failed with an HTTP error. I've confirmed that this fix works for the recent versions of chromedriver and phantomjs that I have installed.

Fix get-window-handles for chrome and phantom

---

src/etaoin/api.clj

Changes deep-merge to concat sequential values
Fixes https://github.com/igrishaev/etaoin/issues/39

Stop overwriting default driver capabilities when merging

---

resources/html/test.html
src/etaoin/api.clj
test/etaoin/api_test.clj

When `#has-text` is used, quotes can't be used because of the use of
single quotes in the xpath query that is created. This commit swaps the
single quotes (') in the query for escaped double quotes (\")
Adds a test case as well

Adds ability to find text with quotes

---

src/etaoin/api.clj

First of all, thank you for your video. It was very good to see your workflow!
I think that the implementation of `scroll-left` and `scroll-right` is inverted.
Considering that the top-left pixel of the page is 0,0, we increase it going down/right.
WDYT?

Invert scroll-left and scroll-right offset calculation

---

src/etaoin/driver.clj
test/etaoin/api_test2.clj

Fix custom marionette port when `:profile` is specified

---

README.md

This fixes:
```
Error: No available formula with the name "chromedriver"
It was migrated from homebrew/core to caskroom/cask.
You can access it again by running:
brew tap caskroom/cask
And then you can install it by running:
brew cask install chromedriver
```

README: update brew for chromedriver

---

README.md

Hi! Just a small improvements to the README getting on the radar `click-el` and `fill-el` for everyone!
This would close #153 of course.
Anyway, take a look at [Cljdoc](https://cljdoc.xyz/), if you feel it is too much of a hassle, I could try to generate docs since I wanted to try that library anyway.

Add `click-el` and `fill-el` examples to README

---

src/etaoin/api.clj
src/etaoin/proc.clj
src/etaoin/util.clj

`lein check` showed a few inter-op calls that needed type hints.

type hints

---

.circleci/config.yml
.circleci/firefox.sh
.gitignore
README.md
test/etaoin/api_test.clj

hello,
thanks for Etaoin! This fixes #158
ETAOIN MAINTAINERS: TODO BEFORE MERGING:
- create project on circleci
- enable building for PR
- update README.md to point to the correct etaoin on circleci :-)
- consider setting the default value for logging to INFO as opposed to DEBUG. All the debug logging just hides the failing tests in my opinion
DETAILS OF COMMIT:
- Select the drivers based on the OS (previously it was attempting
to run Safari on Linux)
- Add .circleci/config.yml configuration file
- Add optional ETAOIN_TEST_DRIVERS environment variable:
By default we run the tests with all the drivers supported on the
current OS. To override this, you can set the environment variable
ETAOIN_TEST_DRIVERS to a Clojure vector encoded as a string; for
example:
ETAOIN_TEST_DRIVERS="[:firefox]" …

Add support for CircleCI

---

.circleci/config.yml
.gitignore
project.clj

When running the tests on CicleCI, emit XUNIT test reports so
that CircleCI call collect and show test statistics.
Tests statistics are shown in two places:
1. Each single build gives an overview of the failing tests. Compare:
- with overview: https://circleci.com/gh/marco-m/etaoin/47
- without overview: https://circleci.com/gh/igrishaev/etaoin/3
2. The build-insights page. Compare:
- with test insights: https://circleci.com/build-insights/gh/marco-m/etaoin/circleci-xunit
- without test insights: https://circleci.com/build-insights/gh/igrishaev/etaoin/master

Collect test run information on CircleCI

---

README.md
src/etaoin/api.clj

Thanks a lot for this wonderful work! I've skimmed the source code and it's been a pleasure to read. At first I was afraid I couldn't tweak it to use a custom browser but actually your code is written with style and extensible so it's as easy as
``` clj
(def firefox-developer-edition-driver
(firefox {:path-browser "/Applications/Firefox Developer Edition.app/Contents/MacOS/firefox"}))
```
Anyway, back to topic! ^^ Actually this small PR intends to fix two things:
- `geckodriver` is currently not a cask but `chromedriver` is.
- Provide access to raw inner HTML, for example to use etaoin in conjunction with [enlive](https://github.com/cgrand/enlive) – or any better ideas for that?
Let me know if there's anything I could do to ease the review / approval process.

Update README.md and add inner HTML getter

---

src/etaoin/api.clj

Hi. I Just spotted a small error in the docstring.

Fix typo in absent? docstring

---

README.md
src/etaoin/api.clj

Currently in `etaoin.api/postmortem-handler` the default `date-format` is `"yyyy-MM-dd-hh-mm-ss"`, but lowercase `hh` stands for [Hour in am/pm (1-12)](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html). Since there is no am/pm marker in the pattern, it was most probably meant to be in 24 hour format which is `HH`. This PR fixes that.

Use 24-hour date format in postmortem-handler

---

src/etaoin/api.clj

Change a link to ChromeDriver source code from my fork of ChromeDriver to the official repository.

Change a link to ChromeDriver source code

---

README.md
src/etaoin/api.clj

* Support for screenshots of elements seems to have been added since ChromeDriver 2.42.   
* Tested successfully with ChromeDriver 74.0.3729.6 from [this test](https://github.com/quil/quil/blob/master/test/clj/quil/snippet.clj#L145).

Add `screenshot-element` support for chrome driver.

---

src/etaoin/api.clj

This is a proposed fix for issue #165.
When running my own UI tests using the Etaoin library on a Linux CI server, my tests seem to fail 30% of the time with a `java.net.SocketException: Connection reset by peer` error.
I have applied this patch to a private repo version of Etaoin and I am no longer seeing failures in my UI tests.
It is possible for an exception to be thrown when calling `close` if data is still being transferred, so I have caught the exception there as well as during `connect`, even though we don't care about the "error on close" message itself.

Fix "Connection reset by peer"

---

src/etaoin/api.clj
test/etaoin/api_test.clj

The test was broken because it was not updated to reflect the changes
in 9aaca669 i.e. `default-interval` and default message for `wait-has-text`.

Fix `test-wait-has-text`. Resolves #10.

---

README.md

Move the section on driver installation to be next to the part on library installation, to avoid confusion by beginners e.g.(https://github.com/igrishaev/etaoin/issues/229). Also fixed typo.

Move driver installation part and typo fix

---

README.md

add example remote connection

---

src/etaoin/api.clj
src/etaoin/util.clj

better free port discovery

---

src/etaoin/api.clj
src/etaoin/driver.clj

fix headless? && save capabilities

---

src/etaoin/api.clj
src/etaoin/driver.clj
test/etaoin/api_test.clj

add edge support

---

README.md
src/etaoin/api.clj
src/etaoin/driver.clj

add http proxy settings

---

README.md
src/etaoin/api.clj
src/etaoin/proc.clj
test/etaoin/api_test2.clj

add logging to files

---

resources/html/test.html
resources/html/test2.html
src/etaoin/api.clj
test/etaoin/api_test.clj

fix switch-window with PhantomJS

---

README.md
resources/html/test2.html
src/etaoin/api.clj
test/etaoin/api_test.clj

add query-tree fn

---

README.md
src/etaoin/api.clj

add wrap-default-timeout && wrap-default-interval

---

README.md

add examples of query functions

---

README.md
src/etaoin/api.clj
test/etaoin/api_test.clj

fix wait-has-text

---

src/etaoin/driver.clj
test/etaoin/api_test2.clj

Fix chrome profile

---

README.md

add a description of the trouble

---

Dockerfile
Makefile
test/etaoin/api_test.clj
test/etaoin/api_test2.clj

make tests run in display mode

---

src/etaoin/api.clj

make service functions private

---

test/etaoin/proc_test.clj

test prevent process fork

---

src/etaoin/api.clj

fix `quit` fn for remote driver

---

README.md

update examples for docker and remote connection

---

README.md

add a description of the trouble with chromedriver

---

project.clj
src/etaoin/ide/flow.clj
src/etaoin/ide/main.clj
src/etaoin/util.clj

add cli entry point for ide

---

README.md
src/etaoin/ide/flow.clj

add docs for ide

---

README.md
src/etaoin/api.clj
src/etaoin/util.clj
test/etaoin/api_test.clj
test/etaoin/unit_test.clj

add macro with-screenshots

---

README.md
src/etaoin/api.clj
test/etaoin/api_test.clj

I noticed that I `wait-visible` did not allow me to add a `:message` key to opts. The default message is helpful, though.
This PR adds default messages to all `wait-predicate` wrappers while allowing the `:message` of `opt` to override them.
Grammatically, "Wait until _query_ element is visible" sounds better to me than "Wait for _query_ element is visible".

Wait messages

---

.circleci/config.yml
CHANGELOG.adoc
Dockerfile
README.md
src/etaoin/api.clj
test/etaoin/api_test.clj

Existing code that supports PhantomJS remains, but we are no longer
launching tests for the, presumably obsolete, PhantomJS.
Closes #388

Stop testing PhantomJS

---

CHANGELOG.adoc
test/etaoin/ide_test.clj

Use existing technique found in api test.
Closes #391

Report browser name (ex. firefox) when ide test fails

---

CHANGELOG.adoc
src/etaoin/api.clj
src/etaoin/client.clj

Other webdriver implementations don't seem to care, but safaridriver
returns a 400 error when, for example, DELETE requests include a body.
Closes #402

Body now sent only for webdriver HTTP POST request

---

CHANGELOG.adoc
src/etaoin/api.clj

Webdriver implementations seem to handle a click directly on the option
element without first click on the select element.
Except for `safaridriver`. It needs us to click on the select element
before clicking on the option element.
This seems like a reasonable general flow, so did not special case for
`safaridriver`.
Closes #403

Fix api select fn for safaridriver

---

CHANGELOG.adoc
resources/ide/test.side

After I noticed firefox was failing to handle state changes for multiple
key modifiers (e.g. shift key) in our ide tests, I did a little digging
and decided that might be actully adhering to the w3c webdriver spec
(see #387 for details).
Closes #387

No longer testing multi key modifiers in send keys

---

CHANGELOG.adoc
src/etaoin/api.clj

Fix switch-window for msedgedriver

---

.clj-kondo/clj-kondo/slingshot/clj_kondo/slingshot/try_plus.clj
.clj-kondo/clj-kondo/slingshot/config.edn
.clj-kondo/config.edn
.clj-kondo/etaoin/api.clj
.clj-kondo/etaoin/util.clj
CHANGELOG.adoc
env/dev/demo.clj
src/etaoin/api.clj
src/etaoin/client.clj
src/etaoin/dev.clj
src/etaoin/driver.clj
src/etaoin/ide/api.clj
src/etaoin/ide/flow.clj
src/etaoin/query.clj
src/etaoin/util.clj
test/etaoin/api_test.clj
test/etaoin/proc_test.clj

Highlights:
- found 1 bug - `etaoin.ide.api` `:storeTitle` command was calling
`etaoin.api/get-title` with wrong number of args. Fixed.
- found an invalid symbol `num-.` from https://clojure.org/reference/reader:
"Symbols beginning or ending with '.' are reserved by Clojure"
Left as is, but will likely follow up with a name change.
Of note:
- Etaoin uses, and might encourage, the use of `:refer :all` for its
api. Ignoring for now. We can decide how we want to do at some later
date.
Other
- Missing require for `clojure.set` added
- An `if` without else converted to `when`. I like this convention, to me it
conveys that an `if` did not accidentally omit an else condition.
- Unused bindings/paramers prefixed with underscore, unless part of
public API and the unuse is an implementation detail. …

Add clj-kondo config - first pass

---

CHANGELOG.adoc
src/etaoin/ide/api.clj
src/etaoin/keys.clj

The symbol `num-.` is technically an invalid Clojure symbol and can
confuse tooling.
Minor breaking change, see changelog for impact.
Closes #412

Rename `etaoin.keys/num-.` to `etaoin.keys/num-dot`

---

test/etaoin/proc_test.clj

Also now closing driver session which closes the window that was always
left open at the end of test runs.
Fixes #382

Proc-test for Windows compensates for scoop

---

test/etaoin/api_test.clj

The test was attempting to make the Window bigger, but for firefox on macOS on
GitHub Actions, this was failing. GitHub Actions macOS has a relatively
small screen size, and firefox won't resize larger if we are at the
limits.
I think we are still covering the spirit of the test if we resize
smaller instead of bigger.
Fixes #419

Window size test now makes window smaller

---

.github/workflows/test.yml
bb.edn
script/tools_versions.clj

Expand testing from ubuntu only to also cover macOS and Windows.
Introduce a babashka task to report tool versions. Babashka was chosen because:
- It is cross-platform, one script to rule them all!
- I prefer it over trying to express myself in yaml
- I prefer it over bash/powerscript
- Scripting in Clojure, I mean c'mon!
Will follow up to complete #392
Closes #381

Run tests on GitHub Actions

---

.clj-kondo/babashka/fs/config.edn
.clj-kondo/lread/status-line/config.edn
.clj-kondo/rewrite-clj/rewrite-clj/config.edn
.github/workflows/test.yml
bb.edn
project.clj
script/helper/main.clj
script/helper/os.clj
script/helper/shell.clj
script/test.clj
script/tools_versions.clj
test/etaoin/api_test.clj
test/etaoin/ide_test.clj
test/etaoin/proc_test.clj
test/etaoin/test_report.clj
test/etaoin/unit_test.clj
test/etaoin/xpath_test.clj

In addition to being broken down by OS, tests are now also broken down by
major type (ide, api, unit) and browser (chrome, firefox, edge, safari)
for ide and api tests.
Observations:
- can now more readily see what we are testing by the job breakdown in
GitHub Actions UI
- nice to have an overall shorter test run. I'm seeing ~8m to completion instead
of the former ~15m
- faster feedback for what is passing/failing
- some windows tests might be a bit flaky, but good to know, so that we can
address, right?
- very nice to be able to rerun a single failed job, for example, if
`unit windows` has failed, I can rerun it alone via the GitHub UI.
The current tests only invoke chrome and firefox for ide testing, so
I've stuck with that. Api testing matches current browser defaults.
I'm liking …

Parallelize tests run on GitHub Actions

---

project.clj
src/etaoin/util.clj

Etaoin was using apache commons.io to delete a tempoarary dir.
This dependency was brought in implicitly by clj-http.
Replaced with babashka/fs delete-tree.
Out of scope: Using more babashka/fs than we need to. This libary
has some great abstractions that I expect will help with maintainability,
we'll get to this later.

road to bb: remove dependency on apache commons.io

---

src/etaoin/proc.clj
test/etaoin/proc_test.clj

Proc was referencing java.lang.IllegalThreadStateException, an exception
that babashka is currently unaware of.
Good news is that the code that referenced this is entirely unused.
Deleted it along with other unused vars.
Also:
- marked private vars as such
- tweaked proc-test to help maybe diagnose flakyness on Windows on CI

road to bb: tweak process support

---

.github/workflows/test.yml
script/tools_versions.clj
test/etaoin/api_test.clj

We were using java's ImageIO to validate that we could successfully read
screenshot png images. There's nothing wrong with this, but babashka
does not currently include ImageIO support.
So I've switch to calling out to Image Magick to validate our screenshot
png are valid.
A minor developer setup burden for bb compatibility.

road to bb: ImageIO no longer used in tests

---

src/etaoin/api.clj
src/etaoin/driver.clj
src/etaoin/util.clj
test/etaoin/api_test.clj
test/etaoin/unit/unit_test.clj

Replaced direct JDK references with babashka fs abstractions.
Of note:
- turfed etaoin.util/with-tmp-dir and replaced its usages with babashka
fs equivalent (Files/createTempDirectory is unavailable in bb, I think).
We've decided that etaoin.util is not part of our public API #430, so not
worried about deleting this macro.
- some references to io/file replaced with fs/file for more flexible coercion.

road to bb: more babashka fs usage

---

CHANGELOG.adoc
bb.edn
deps.edn

Also: specify minimum babashka version.
Closes #446

Bump dependencies to current releases

---

.clj-kondo/config.edn
CHANGELOG.adoc
bb.edn
deps.edn
doc/01-user-guide.adoc
doc/02-developer-guide.adoc
doc/user-guide-sample-frame1.html
doc/user-guide-sample-frame2.html
doc/user-guide-sample.html
env/dev/demo.clj
resources/clj-kondo.exports/etaoin/etaoin/config.edn
resources/clj-kondo.exports/etaoin/etaoin/etaoin/api.clj_kondo
script/test.clj
script/test_doc.clj
src/etaoin/api.clj
src/etaoin/api2.clj
src/etaoin/dev.clj
src/etaoin/ide/flow.clj
src/etaoin/ide/impl/api.clj
src/etaoin/ide/main.clj
src/etaoin/impl/client.cljc
src/etaoin/impl/driver.clj
src/etaoin/impl/proc.clj
src/etaoin/query.clj
test/etaoin/api_test.clj
test/etaoin/ide_test.clj
test/etaoin/unit/proc_test.clj
test/etaoin/unit/unit_test.clj
test/etaoin/unit/xpath_test.clj

New maintainer preference is to not use `:refer :all` in code and docs.
This is subjective, so apologies to those who prefer `:refer :all`.
This change should not affect behaviour of Etaoin.
I tried to be consistent in aliasing. For example `etaoin.api :as e`.
Also did a clojure-lsp clean-ns on each `ns`.
Deleted extra whitespace (newlines) when I noticed.
While sweeping the user guide:
- attempted to understand everything I read, and elaborated where I,
as a relative newcomer to Etaoin, was confused
- attempted a re-org to group related sections together
- reworded some sentences here and there
- add a section on creating the driver
- updated outdated text where I noticed it
- attempted to make most example code blocks something the user could
theoretically paste and run (and verified …

User guide and usage related updates

---

CHANGELOG.adoc
README.adoc
deps.edn
doc/01-user-guide.adoc
doc/02-developer-guide.adoc
src/etaoin/api.clj
src/etaoin/api2.clj
src/etaoin/dev.clj
src/etaoin/ide/flow.clj
src/etaoin/ide/main.clj
src/etaoin/keys.clj
src/etaoin/query.clj

Did a sweep through the current Etaoin public API.
Changes to public API can be seen as an addendum to #430.
Consistency - exposed as part of public API (were formerly private)
- etaoin.api
- get-element-value-el
- get-element-property-el
- get-element-css-el
Maintainability - deleted
- etaoin.api (used for pointer move action only, moved into fn)
- default-duration
- default-origin
Maintainability - no longer exposed (now implementation details)
My default was to make private, but because some are used from macros
this did not always work. For those cases I just marked with :no-doc
metadata:
- etaoin.api
- default-locator
- dispatch-driver
- find-elements*
- format-date
- get-pwd
- join-path
- locator-css
- locator-xpath
- make-screenshot-file-path
- make-url
- postmortem-handler
- …

API review: docstrings, arglists, publics

---

src/etaoin/api.clj

This one is use from a macro, so it cannot be private.

Switch with-exception from private to no-doc

---

CHANGELOG.adoc
doc/01-user-guide.adoc

docs: user-guide: describe execute fn 

---

CHANGELOG.adoc
doc/01-user-guide.adoc
src/etaoin/api.clj

Exposed as `print-page` (avoids conflict with clojure.core/print).
Closes https://github.com/clj-commons/etaoin/issues/355

Expose W3C WebDriver print to PDF feature

---

CHANGELOG.adoc
doc/01-user-guide.adoc
src/etaoin/api.clj
src/etaoin/impl/driver.clj
src/etaoin/impl/util.clj
test/etaoin/unit/unit_test.clj

Also:
- no longer add nil driver map values
- add `defaults-global` for defaults that apply to all driver types
- add some more tests around created driver map
- localized handling of most driver option defaults to one spot
Closes #471

Driver defaults :path renamed to :path-driver

---

doc/01-user-guide.adoc
src/etaoin/api.clj
src/etaoin/impl/util.clj
test/etaoin/unit/unit_test.clj

This allows us to compensate for mysterious, but recoverable,
safaridriver failed launches.
Default for safaridriver is set to 4 retries (total of 5 attempts).
Also host/port socket connectivity check updated to:
- include an explicit timeout of 1 second
- always close socket no matter what happens
Closes #468

Allow retry on failed WebDriver process launch

---

CHANGELOG.adoc
src/etaoin/api.clj
src/etaoin/impl/client.cljc
test/etaoin/unit/proc_test.clj

When an http request, for example, times out one might wonder if the
WebDriver process is still running.
We now use slingshot throw+ as we do for http status errors. This throw+
still includes the :driver :process but checks if it is alive and
realizes its exit value in the thrown map if dead.
Also: if an exception occurs when booting a driver, any launched WebDriver
process is now cleaned up.
Also: reworked some proc tests to always attempt cleanup even when
exceptions occur.
Closes #469

Include driver process liveness in some exceptions 

---

CHANGELOG.adoc
env/test/resources/html/test.html
src/etaoin/api.clj
test/etaoin/api_test.clj

We have learned that displayed-ness is more complex than we had
originally imagined. It requires more research and maybe more hammock
time.
Effectively rolls back PR #445 for issue #444.

Rollback our work on displayed? api function

---

.github/workflows/release.yml
CHANGELOG.adoc
bb.edn
build.clj
deps.edn
doc/03-maintainer-guide.adoc
doc/cljdoc.edn
script/ci_release.clj
version.edn

Mostly cribbed from rewrite-clj.
Currently invoked from GitHub Actions UI.
Version scheme is major.minor.release-count
See new maintainer guide for details.
Closes #422

Add automated release workflow

---

.github/workflows/release.yml
.github/workflows/test.yml

ci: adapt to GitHub actions set-output deprecation

---

CHANGELOG.adoc
src/etaoin/api.clj

JDK 19's Thread/sleep now also accepts a Duration. Add a ^long type hint to remove this new ambiguity for Clojure interop.
Closes #503

Address JDK 19 Thread/sleep Clojure interop

---

.github/workflows/test.yml
CHANGELOG.adoc
Dockerfile
bb.edn
doc/01-user-guide.adoc
script/test.clj

Geckodriver stopped compensating in the absence of a windows manager on Linux.
Xvfb, our virtual display tech on Linux, does not include a windows manager.
We compensate with the fluxbox windows manager.
Also:
- while testing fluxbox, updated our Dockerfile to use clojure docker image. The clojure docker images are well maintained and, awesomely, include clojure.
Closes #447

Setup windows manager for Firefox on Linux

---

.github/workflows/release.yml
.github/workflows/test.yml

This might get rid of GitHub Action deprecation warning about save-state

Bump setup-clojure action

---

.github/workflows/test.yml
CHANGELOG.adoc
bb.edn
deps.edn
doc/01-user-guide.adoc
doc/02-developer-guide.adoc
script/bb_test_runner.clj
script/test.clj
script/test_matrix.clj
test/etaoin/ide_test.clj

The new test:bb and test:jvm bb tasks replace the test task. I think this makes bb and jvm platform tests easier to discover.
Extracted out test matrix generation to its own test-matrix bb task (was formerly invoked via a test task cmd line arg).
Now employing babashka cli for test tasks.
Using for both test:jvm and test:bb.
Can now choose to run individual tests vars and namespaces. Our test tasks now accept --nses --patterns and --vars options which we pass thru to the cognitect test runner.
Updates to babashka allow us to now no longer rely on babashka:
- namespace fork (was need for test runner)
- babashka spec.alpha fork (ide feature relies on spec.alpha). Closes #507
For consitency:
- dev task renamed to dev:jvm
- dev-bb task renamed dev:bb. Adjusted this one to match test:bb re …

Refine unit tests

---

bb.edn

The dev:bb task now promises to stick around.

Fix: bb repl exited right after launch [skip ci]

---

bb.edn
doc/02-developer-guide.adoc

And docker-run docs updated to use new test tasks

fix: docker-run now properly supports interactive

---

.github/workflows/test.yml

GitHub Actions has added ImageMagick to their Windows images so we no longer need to install it.
Closes #531

ci: ImageMagick is now pre-installed for windows

---

.github/workflows/release.yml
.github/workflows/test.yml
CHANGELOG.adoc
deps.edn

Of note, running tests was causing:
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "clojure.lang.Named.getNamespace()" because "x" is null 
Not sure why this started to happen, but bumping all deps resolved the issue.
The following failures are expected and will be addressed separately:
- api macos safari bb/jvm #537 
- api windows edge bb/jvm #538

maint: bump deps

---

.github/workflows/test.yml
bb.edn
script/gha_win_edge_workaround.clj
script/tools_versions.clj

A temporary fix to address a bug in the GitHub Actions Windows runner: it includes the wrong version of the Edge Webdriver.
Can delete this temp fix when GHA resolves their problem.
Closes #538
The following failures are expected and will be addressed separately:
- api macos safari bb/jvm #537 

ci: temp fix for edge webdriver version mismatch

---

test/etaoin/api_test.clj

We'll ignore the new `sameSite` data in cookies response for now.
Refactored existing same strategy for Firefox to localize/match.
Closes #537

tests: Safari cookies response has new data

---

CHANGELOG.adoc
doc/01-user-guide.adoc
doc/user-guide-sample.html
src/etaoin/api.clj

Clearly explain that `etaoin.api/select` is a convenience function and add examples to user guide on other ways to select options from dropdowns.
User guide is run through test-doc-blocks so new example code blocks are verified and part of our test suite.
Closes #534

docs: selecting options from dropdowns

---

doc/01-user-guide.adoc

I've been noticing a sporadic "stale element" error when running wikipedia examples through test-doc-block.
I'm thinking it might be related to how wikipedia implemented their type-ahead search.
Maybe someday we'll automatically retry on stale element errors, but for now I've introduced a 1 second wait to try and de-flake these examples.

test-doc: user guide: de-flake wikipedia example

---

CHANGELOG.adoc
CONTRIBUTING.md
README.adoc
doc/01-user-guide.adoc
src/etaoin/api.clj
test/etaoin/api_test.clj

Previously, when `api/fill-human` was asked to write text that contained emojis (or other "wide" characters) it would end up writing `??` to the input field instead of the actual emoji. The reason for this is that it was just iterating over every character in the string instead of over the codepoints.
This PR adds support for wide characters to `api/fill-human` by iterating over its codepoints.
Closes #551 
[wokring-codepoints.webm](https://user-images.githubusercontent.com/3422347/235228554-9e1de8cc-4660-4397-b6f6-fd6388130d89.webm)
---

Add support for wide characters to `fill` functions

---

.clj-kondo/http-kit/http-kit/config.edn
.clj-kondo/http-kit/http-kit/httpkit/with_channel.clj
.github/workflows/release.yml
.github/workflows/test.yml
deps.edn
test/etaoin/api_test.clj
test/etaoin/ide_test.clj
test/etaoin/test_report.clj

Of note:
- address new clj-kondo findings (dynamic tests vars were uninitialized).

maint: bump deps to current

---

.github/workflows/test.yml
script/test_matrix.clj
src/etaoin/api.clj

Addendum for #552
Add jdk variants for CI.
Default to jdk 21 but also sanity test on jdks 8, 11 and 17.

Fix jdk8 compatibility

---

CHANGELOG.adoc
src/etaoin/impl/driver.clj
test/etaoin/api_with_driver_test.clj

Also add in sanity tests for WebDrivers that recognize `:driver-log-level`.
Closes #566

Fix: recognized `:driver-log-level` for Edge

---

doc/01-user-guide.adoc

This is just a small fix to reference the correct commands, as documented by the CLI help messages, in the docs. I don't know if all of the above applies to such a small, non-code change? :)

Fix test command references in user guide

---

.github/workflows/test.yml
doc/01-user-guide.adoc
script/test_matrix.clj
test/etaoin/unit/unit_test.clj

ci changes

---

CHANGELOG.adoc
bb.edn
doc/01-user-guide.adoc
script/docker_install.clj
script/drivers.clj
script/helper/ps.clj
src/etaoin/ide/main.clj
src/etaoin/impl/proc.cljc
test/etaoin/api_test.clj
test/etaoin/ide_test.clj
test/etaoin/unit/proc_test.clj
test/etaoin/unit/unit_test.clj

Our tests included the `--no-sandbox` option for chrome.
This seems to have been harmless until recently.
On Windows, it now results in orphaned chrome processes which results in tests bogging and then, after a long, while failing.
Removing `--no-sandbox` when running on Windows resolves the issue.
The `--no-sandbox` option allows testing under a root user. Because we don't run tests under root on any OS or environment, I feel comfortable removing `--no-sandbox` across all OS testing.
This change also includes new bb task `ps`, a bare-bones cross-platform way to report on running processes. This was useful while diagnosing the issue so I've left it in.
I also switched from `babashka.process/destroy` to `babashka.process/destroy-tree` when killing a web driver process. This did not help …

Remove chrome's `--no-sandbox` from tests

---

bb.edn
doc/02-developer-guide.adoc

Allows developer to specify `--host 0.0.0.0` to allow anyone to remotely connect. Handy when debugging behaviour on VM or other computer.
Closes #578

dev: add `--host` to `dev:bb` and `dev:jvm` tasks

---

env/test/resources/static/test2.html
test/etaoin/api_test.clj

Safaridriver is not great with mouse clicks, press enter on link to create new target window instead.
- `test-switch-window` - assert window count earlier for clearer failures
- `test-switch-window-next` - was using unrealized `repeat`s so was effectively testing nothing. Reviewed and rewrote with some compensations for our odd little safaridriver.
Closes #579

tests: fix window switch tests

---

.clj-kondo/taoensso/encore/config.edn
.clj-kondo/taoensso/encore/taoensso/encore.clj
.gitignore
bb.edn
deps.edn
src/etaoin/api.clj
src/etaoin/api2.clj
src/etaoin/dev.clj
src/etaoin/ide/flow.clj
src/etaoin/ide/impl/api.clj
src/etaoin/ide/impl/spec.clj
src/etaoin/ide/main.clj
src/etaoin/impl/client.cljc
src/etaoin/impl/driver.clj
src/etaoin/impl/proc.cljc
src/etaoin/impl/util.clj
src/etaoin/impl/xpath.clj
src/etaoin/keys.clj
src/etaoin/query.clj
test/etaoin/api_test.clj
test/etaoin/ide_test.clj
test/etaoin/unit/unit_test.clj

For some other Etaoin wip, I wanted to address some reflection warnings for new code and noticed we did not have any existing checks for reflection. I find Eastwood helps out with this nicely.
In addition to reflection warnings, I also addressed some other issues Eastwood reported:
- A booboo in a test assertion for `etaoin.unit.unit-test/test-chrome-profile`.
Fixed!
- URL constructors are deprecated, starting with JDK 20. I switched to using lambdaisland/uri.
- it noticed `is` assert messages that were not obviously strings. I ^String type hinted the message generating fn.
- it thought string `"always"` for a constant truthy looked suspicious. I switched to the more conventional `:always`.
- several tests had empty assertions like `(is true "text found")` or `(is 1)`.
Perhaps some linter …

dev: add Eastwood linting

---

test/etaoin/unit/unit_test.clj

Something changed somewhere to trigger this, but we should have been comparing real paths all along.
Fixes #582

tests: `test-chrome-profile`: compare real paths

---

Dockerfile
doc/01-user-guide.adoc
doc/02-developer-guide.adoc
script/docker_install.clj
script/tools_versions.clj

- bump to jdk21
- install chrome and chromedriver from Chrome for Testing
- chrome launcher name has changed from `google-chrome` to `chrome`, allow for both
- test and install any missing packages
- show progress when downloading drivers/browsers when building image
- old tricks for detecting if we are running from a docker build no longer work, go for a simple file presence check instead
- we don't need `--no-sandbox` for chrome as we are not running from a root user, so we don't need our chrome wrapper
Closes #575

Freshen dev docker test image

---

.gitignore
script/cljdoc_preview.clj

For security reasons, docker is no longer so happy to write to tmp, so move our cljdoc db dir to `~/.cljdoc-preview`.
Also minor babashka modernizations.

dev: cljdoc-preview tweaks [skip ci]

---

test/etaoin/api_test.clj
test/etaoin/unit/proc_test.clj

We can turf this change if we solve the flakiness.

ci: show webdriver output for flaky os/browsers

---

bb.edn
script/tools_versions.clj

Stop using doric table, it was wide and wrapped unless terminal was also wide.
Add in warnings when chrome/chromedriver and edge/edgedriver versions do not match.

dev: rework tools-versions tasks

---

CHANGELOG.adoc
doc/01-user-guide.adoc

Added a complete list of :fn/* functions that are available in the map syntax. This includes everything in impl/xpath.clj, including :fn/has-string.
- [ x] I have read [CONTRIBUTING](https://github.com/clj-commons/etaoin/blob/master/CONTRIBUTING.md) and the [Etaoin Developer Guide](https://github.com/clj-commons/etaoin/blob/master/doc/02-developer-guide.adoc).
- [ x] This PR corresponds to an issue that the Etaoin maintainers have agreed to address. 
- [ x] This PR contains test(s) to protect against future regressions
- [ x] I have updated [CHANGELOG.adoc](https://github.com/clj-commons/etaoin/blob/master/CHANGELOG.adoc) with a description of the addressed issue.

doc: user-guide: add list of :fn/*

---

CHANGELOG.adoc
doc/01-user-guide.adoc
doc/user-guide-sample.html
env/test/resources/static/test.html
src/etaoin/api.clj
test/etaoin/api_test.clj

- [x ] This PR corresponds to an issue that the Etaoin maintainers have agreed to address. 
- [x ] This PR contains test(s) to protect against future regressions
- [x ] I have updated [CHANGELOG.adoc](https://github.com/clj-commons/etaoin/blob/master/CHANGELOG.adoc) with a description of the addressed issue.

Add support for shadow DOM #604

---

CHANGELOG.adoc
doc/01-user-guide.adoc
env/test/resources/static/test.html
src/etaoin/impl/xpath.clj
test/etaoin/api_test.clj

This adds `:fn/index` as a preferred synonym for `:index`, which remains. The docs have been updated to discuss `:fn/index` and `:index` is not mentioned. If both `:fn/index` and `:index` are included in a query map, the value associated with `:fn/index` overrides the value associated with `:index` and `:index` is otherwise ignored.
- [x ] This PR corresponds to an issue that the Etaoin maintainers have agreed to address. 
- [x ] This PR contains test(s) to protect against future regressions
- [x ] I have updated …

Add :fn/index as alias for :index in map syntax

---

CHANGELOG.adoc
bb.edn
doc/01-user-guide.adoc
script/fake_driver.clj
src/etaoin/api.clj
src/etaoin/impl/driver.clj
test/etaoin/api_test.clj
test/etaoin/api_with_driver_test.clj
test/etaoin/unit/unit_test.clj

Safaridriver logging is relatively odd. It only has debug level logging, only logs to a file, and discovering that file is somewhat tricky.
This change adds minimal support to discover and dump safaridriver logs.
I'm not sure how many folks bother with safaridriver testing, so this change might be mostly a favour to myself when diagnosing safaridriver issues that arise from time to time.
Closes #563
Incidentally fixes #517

Minimal safari driver logging

---

.cljfmt.edn
CHANGELOG.adoc
doc/01-user-guide.adoc
doc/02-developer-guide.adoc
resources/clj-kondo.exports/etaoin/etaoin/config.edn
script/drivers.clj
src/etaoin/api.clj
src/etaoin/api2.clj
src/etaoin/ide/main.clj
src/etaoin/impl/driver.clj
test/etaoin/api_test.clj

PhantomJS is long obsolete, and we dropped testing for it long ago. Supporting API, code and docs are clutter at this point.
Closes #612

minor breaking: Remove support for PhantomJS

---

.clj-kondo/config.edn
CHANGELOG.adoc
bb.edn
deps.edn
doc/01-user-guide.adoc
doc/02-developer-guide.adoc
env/test/resources/static/test.html
script/test_coverage.clj
src/etaoin/api.clj
src/etaoin/impl/driver.clj
test/etaoin/api_test.clj
test/etaoin/api_with_driver_test.clj
test/etaoin/unit/unit_test.clj

We've been using a `capabilities` syntax for create session that has long been deprecated. Firefox finally forced our hand with geckodriver 0.35.0, which has removed support for the obsolete syntax.
All supported WebDrivers understand the newer syntax.
We used to pass capabilities in as `desiredCapabilities`, we now pass them in as a single item in the `firstMatch` vector. This should match existing behaviour.
Moving to the new capabilities syntax tells `chromedriver` (and `msedgedriver`) that we are running in "w3c mode". This has benefits on Etaoin code. Our many customizations for these WebDrivers are no longer necessary, they now support the W3C WebDriver endpoint spec.
In "w3c mode", chromedriver disallows any endpoints that could be served by W3C WebDriver endpoints.
Notable …

Move to w3c WebDriver spec

---

deps.edn
script/lint.clj

Of note:
- take advantage of clj-kondo's new ability to copy configs and create cache at same time.

maint: bump deps to current releases

---

.github/workflows/test.yml

There is not always an exact version match of msedgedriver to Edge.
Closes #624

ci: fix msedgedriver download

---

.clj-kondo/config.edn
CHANGELOG.adoc
deps.edn
doc/01-user-guide.adoc
env/test/resources/static/test.html
src/etaoin/api.clj
test/etaoin/api_test.clj

This PR implements the changes described in the discussion of Issue #559.
It specifically:
- Adds `query-from` and `query-all-from`.
- Deprecates both `child` and `children`.
- Makes `get-active-element` a public API.
- Deprecates the use of `:active` as a query parameter to `query` and updates doc strings and user guide to suggest the use of `get-active-element` instead.
- [x ] This PR corresponds to an issue that the Etaoin maintainers have agreed to address. 
- [x ] This PR contains test(s) to protect against future …

Issue #559

---

src/etaoin/api.clj

Convert (-> ... first second) idiom to unwrap-webdriver-object. This should provide better error reporting in case one of the WebDriver implementations has a regression or otherwise starts returning things in a different format.
Closes #620.
- [ x] I have read [CONTRIBUTING](https://github.com/clj-commons/etaoin/blob/master/CONTRIBUTING.md) and the [Etaoin Developer Guide](https://github.com/clj-commons/etaoin/blob/master/doc/02-developer-guide.adoc).
- [ x] This PR corresponds to an issue that the Etaoin maintainers have agreed to address. 
- [ x] This PR contains test(s) to protect against future regressions
- [ x] I have updated [CHANGELOG.adoc](https://github.com/clj-commons/etaoin/blob/master/CHANGELOG.adoc) with a description of …

Use unwrap-webdriver-object

---

CHANGELOG.adoc
src/etaoin/api.clj

Updated CHANGELOG for issue #620

---

CHANGELOG.adoc
src/etaoin/api.clj
test/etaoin/api_test.clj

Implements `fill-active-human`.
Closes #629.

Implement fill-active-human (#629)

---

src/etaoin/api.clj

Point user at fill-human-el for details on `opts`.
Closes issue #637.
- [x ] This PR corresponds to an issue that the Etaoin maintainers have agreed to address. 
- [x ] This PR contains test(s) to protect against future regressions (NOT NEEDED)
- [x ] I have updated [CHANGELOG.adoc](https://github.com/clj-commons/etaoin/blob/master/CHANGELOG.adoc) with a description of the addressed issue. (NOT NEEDED)

Revise fill-human-* doc strings

---

CHANGELOG.adoc
doc/01-user-guide.adoc
src/etaoin/api.clj
test/etaoin/api_test.clj

Closes #642 
- [x ] This PR contains test(s) to protect against future regressions
- [x ] I have updated [CHANGELOG.adoc](https://github.com/clj-commons/etaoin/blob/master/CHANGELOG.adoc) with a description of the addressed issue.

Add `driver-type`

---

CHANGELOG.adoc
src/etaoin/api.clj

Closes #644 
- Marks `when-predicate` and `when-not-predicate` as deprecated.
- Leaves them in the namespace TOC for now.
- Updates doc strings to suggest using `when` and `when-not` instead.
- Updates CHANGELOG with note about the change.
- Rewrites various other macros that previously used `when-predicate` and `when-not-predicate` to use `when` and `when-not` instead.

Deprecate when-predicate and when-not-predicate

---

CHANGELOG.adoc
src/etaoin/api.clj
test/etaoin/api_test.clj

This fits in better with the naming conventions that Etaoin has adopted previously. Compare, for instance, fill-multi and fill-human-multi versus fill-active and fill-human-active.
Amendment to #629 

Change fill-active-human to fill-human-active

---

CHANGELOG.adoc
src/etaoin/api.clj
src/etaoin/ide/impl/api.clj
src/etaoin/query.clj
test/etaoin/api_test.clj

Closes #633 
It turns out that there isn't much low hanging fruit to move things from `:no-doc` to `:private`. There are just too many niggling dependencies between various macros in `etaoin.api` and other functions in other namespaces. While this could be done easily enough by moving implementation-related functions into an implementation namespace, that would be a more drastic change. So, not wanting to break our pick on this, we're going to leave it here.

`:no-doc` to `:private`

---

CHANGELOG.adoc
src/etaoin/api.clj

Previously, if the user supplied a vector argument to fill-multi or fill-human-multi, Etaoin would convert the vector to a map, then convert the map to a sequence of MapEntry pairs, and use those to fill multiple fields. Unfortunately, this threw away all the ordering information in the vector. This change processes the vector as a sequence of partitioned pairs and thereby keeps the order intact.
Closes #649 

Make vector arg to fill-multi/fill-human-multi fill in order

---

CHANGELOG.adoc
src/etaoin/impl/util.clj
test/etaoin/api_test.clj

Make `set-<xyz>-timeout` more resilient to non-integer timeout values

---

CHANGELOG.adoc
doc/01-user-guide.adoc
src/etaoin/api.clj

Docs: Correctly describe behavior when query's parameter is a string

---

CHANGELOG.adoc
src/etaoin/impl/xpath.clj
test/etaoin/unit/xpath_test.clj

Fix :fn/enabled

---

CHANGELOG.adoc
src/etaoin/api.clj

Throw a more accurate exception when query vector is empty

---

.clj-kondo/config.edn
CHANGELOG.adoc
env/test/resources/static/test.html
test/etaoin/api_test.clj

This PR is filed against #640 but the issue should remain open as there are more tests and PRs coming.

Improved test coverage

---

CHANGELOG.adoc
src/etaoin/api.clj
src/etaoin/impl/util.clj
src/etaoin/query.clj

Replace etaoin.impl.util/error with Slingshot throw+

---

CHANGELOG.adoc
src/etaoin/impl/xpath.clj
test/etaoin/api_test.clj

Throw exception for unknown :fn/* function keywords

---

CHANGELOG.adoc
test/etaoin/api_test.clj

Closes #646
Closes #674 
This macro uses wait-predicate to poll the WebDriver for a change in the URL, thus eliminating some race conditions that were causing flaky test failures.

Add wait-url-change macro to make tests more reliable

---

test/etaoin/api_test.clj

Note that this DOESN'T fully close 640. It's just a snapshot of current work.

Improve test cases

---

.github/workflows/test.yml
CHANGELOG.adoc
src/etaoin/api.clj
test/etaoin/api_test.clj

Add new-window API to expose WebDriver's New Window endpoint

---

CHANGELOG.adoc
script/fake_driver.clj
src/etaoin/api.clj
test/etaoin/unit/proc_test.clj
test/etaoin/unit/unit_test.clj

Fix random error in `with-driver-tests`

---

CHANGELOG.adoc
src/etaoin/api.clj

Fix `fill-human-multi`

---

.clj-kondo/config.edn
.clj-kondo/taoensso/encore/config.edn
.clj-kondo/taoensso/encore/taoensso/encore.clj
.github/workflows/publish.yml
.github/workflows/test.yml
CHANGELOG.adoc
bb.edn
deps.edn
script/docker_install.clj
script/publish.clj
script/test_matrix.clj
src/etaoin/api.clj

Of note:
- Bumped lib dep babashka/http-client
- New clj-kondo linter founder redundant str calls! Cool! Fixed!
- Clj-kondo redundant-ignore (now on by default) might be amiss with regards to custom hook linters. It was thinking our test ignore for `:etaoin/empty-opts` could be removed. This is not the case, I'll follow up over at clj-kondo.
- Added jdk23 to CI mix.

ci & dev & lib: bump deps

---

.github/workflows/publish.yml
.github/workflows/test.yml
bb.edn
deps.edn
script/test_matrix.clj

Of note:
- ci matrix bump of jdk23->jdk24
- noticed some hold-backs of deps due to jdk8 compat, but we are now jdk11+

test & ci: bump deps

---

test/etaoin/api_test.clj

While diagnosing some safari on macos and firefox on windows I had turned on logging for ci.
We can turn it back on if need be, but for now it is more noisy than helpful. And I suspect, might have been slowing ci testing for safari.

ci: turf off verbose logging for some tests

---

CHANGELOG.adoc
src/etaoin/impl/client.clj

Etaoin uses cheshire which uses jackson.
Jackson implemented, for security reasons, processing limits. Starting with cheshire 6.0.0 these jackson limits are configurable.
The default json input string length for jackson is 20mb. This is small for Etaoin, a webdriver will return a base64 encoded pdf for a print page request.
We've bumped the json input string limit to ~2gb.
Closes #691

Allow for large json strings in webdriver response

---

doc/01-user-guide.adoc
env/test/resources/ide/test.side
env/test/resources/static/test.html
test/etaoin/api_test.clj

On this os/browser, autocomplete was sometimes interfering with fill human enough to cause test failures.
Resolve by adding `autocomplete="off"` to html test page.
Closes #646
Also:
- rename `password` in html input to `passphrase` to avoid github actions masking what it thinks is sensitive data on test failure
- refresh browser in `input-test` for each `testing` block for better isolation
- test helper fns `wait-url-change` and `reload-test-page` now take a `driver` arg instead of using `*driver*` for easier reuse in REPL testing.

test: fix sporadic fill human errors on macos edge

---

.clj-kondo/imports/taoensso/encore/config.edn
.clj-kondo/imports/taoensso/encore/taoensso/encore_hooks.clj
.github/workflows/test.yml
bb.edn
deps.edn
doc/01-user-guide.adoc
script/test.clj
test/etaoin/api_test.clj

maint: bump deps & misc tweaks
