clj-commons/etaoin

README.md

Adding the company I work for (Barrick Gold) to the list of companies that use etaoin.

add barrick gold

---

src/etaoin/api.clj

84 headless? fix

---

CHANGELOG.md
src/etaoin/api.clj
test/etaoin/api_test.clj

16 mp path

---

.gitignore
CHANGELOG.md
README.md
src/etaoin/api.clj

69 pm logs

---

CHANGELOG.md
README.md
src/etaoin/api.clj
src/etaoin/driver.clj

62 profile

---

CHANGELOG.md
Makefile
README.md
project.clj
src/etaoin/api.clj
src/etaoin/legacy.clj
test/etaoin/api_test.clj

Clojure 1.7 supprted

---

CHANGELOG.md
README.md
project.clj
src/etaoin/api.clj
src/etaoin/util.clj

88 js async

---

resources/html/test.html
src/etaoin/api.clj
test/etaoin/api_test.clj

Add support for reading element properties

---

CHANGELOG.md
README.md
src/etaoin/api.clj
src/etaoin/driver.clj

73 download dir

---

README.md
resources/html/simple.html

105 readme updated

---

CHANGELOG.md
Makefile
README.md
project.clj
src/etaoin/api.clj
src/etaoin/xpath.clj
test/etaoin/xpath_text.clj

114 query lang

---

README.md

117 readme updated

---

CHANGELOG.md
README.md
src/etaoin/api.clj

134 screen el

---

CHANGELOG.md
README.md
project.clj
resources/html/test.html
src/etaoin/api.clj
src/etaoin/xpath.clj
test/etaoin/api_test.clj

116 has text

---

README.md

Note that the badge will show NO BUILDS because CircleCI doesn't
build yet https://circleci.com/gh/igrishaev/etaoin.

Point the CircleCI badge upstream (https://circleci.com/gh/igrishaev)

---

test/etaoin/api_test.clj

Hello,
is this what you had in mind ?

Unclumsify selection of drivers in tests following PR comments

---

README.md

We recently started using etaoin at Adzerk for our UI frontend tests.
We're enjoying it so far, excellent work! :+1:

Add Adzerk to the "Who uses it?" list

---

README.md

We recently re-branded, which included changing "Room Key" to "Roomkey".

Update company name in readme (Room Key -> Roomkey)

---

src/etaoin/api.clj
test/etaoin/api_test.clj

move safari from jwp to w3c protocol

---

project.clj

bump clj-http && cheshire

---

src/etaoin/legacy.clj
test/etaoin/api_test.clj

better legacy code

---

resources/html/test.html
src/etaoin/api.clj
test/etaoin/api_test.clj

add select fn

---

src/etaoin/api.clj
src/etaoin/client.clj
src/etaoin/dev.clj
src/etaoin/driver.clj
src/etaoin/util.clj
src/etaoin/xpath.clj
test/etaoin/api_test.clj
test/etaoin/api_test2.clj

Aggressive indent

---

project.clj
src/etaoin/util.clj

fix reflection warning && indent project.clj

---

README.md

add fixture example

---

README.md

add test examples

---

README.md

add docker examle

---

README.md
src/etaoin/api.clj

add opts for human input

---

Dockerfile

fix installation geckodriver in docker

---

README.md
src/etaoin/api.clj
src/etaoin/proc.clj

add setting of env

---

Dockerfile

fix geckodriver install

---

test/etaoin/api_test.clj

fix test-cookies for newest firefox

---

src/etaoin/api.clj

add pre checks for query fns

---

.circleci/config.yml
Dockerfile

add phantomjs to docker && circleci

---

src/etaoin/api.clj
test/etaoin/api_test.clj

fix get-inner-html for phantomjs

---

src/etaoin/api.clj

fix creating dirs in postmortem handler

---

src/etaoin/api.clj

make some declarations private for :use

---

README.md
src/etaoin/api.clj

add fn `select` decription && some fix

---

src/etaoin/api.clj

decrease default timeout

---

README.md
src/etaoin/xpath.clj
test/etaoin/xpath_test.clj

add :fn/link

---

README.md
src/etaoin/api.clj
test/etaoin/api_test.clj

add fill human multi

---

src/etaoin/api.clj

add click on field to fill-human

---

src/etaoin/api.clj
test/etaoin/api_test2.clj

move session opts from run- to connect- driver

---

resources/html/test.html
src/etaoin/xpath.clj
test/etaoin/api_test.clj
test/etaoin/xpath_test.clj

fix :fn/text && :fn/has-text

---

README.md

add example for query-all

---

README.md

fix example for docker

---

src/etaoin/dev.clj

fix get-performance-logs

---

README.md
src/etaoin/api.clj
src/etaoin/driver.clj

add log level fo driver

---

src/etaoin/driver.clj
test/etaoin/api_test2.clj

fix chrome profile test && reflect warn

---

test/etaoin/api_test2.clj

freeze chrome profile test

---

Makefile

add x11 for tests

---

src/etaoin/api.clj
test/etaoin/api_test2.clj

https://github.com/igrishaev/etaoin/issues/295

add fns for connecting to remote drivers

---

Makefile

fix check $HOST

---

src/etaoin/xpath.clj
test/etaoin/api_test.clj
test/etaoin/xpath_test.clj

add :fn/has-string && return old version has-text

---

test/etaoin/api_test2.clj

add `with-tmp-dir` for tests

---

src/etaoin/api.clj
src/etaoin/client.clj
src/etaoin/driver.clj
src/etaoin/query.clj
test/etaoin/api_test2.clj
test/etaoin/proc_test.clj

get rid of atom storage

---

README.md

add release notes

---

README.md
src/etaoin/api.clj

add description for actions

---

resources/html/test.html
resources/ide/test.side
src/etaoin/api.clj
src/etaoin/ide.clj
test/etaoin/ide_test.clj

add ide methods

---

resources/ide/test.side
src/etaoin/ide.clj
test/etaoin/ide_test.clj
test/etaoin/unit_test.clj

add control flow for ide

---

resources/html/test.html
resources/html/test2.html
resources/ide/test.side
src/etaoin/ide.clj
test/etaoin/ide_test.clj

add tests for ide

---

resources/ide/test.side
src/etaoin/api.clj
src/etaoin/ide/api.clj
test/etaoin/api_test.clj
test/etaoin/ide_test.clj

add support firefox for ide

---

.circleci/config.yml
env/test/resources/log4j.properties
project.clj

fix circleci config

---

src/etaoin/api.clj
test/etaoin/api_test.clj

add multiple clicks

---

src/etaoin/api.clj
test/etaoin/api_test.clj

add switch window next

---

README.md

At Guaranteed Rate, we use Etaoin to end-to-end test our digital mortgage application.

Add Guaranteed Rate to companies using Etaoin

---

src/etaoin/api.clj

This fixes double click on chromedriver as per #367 
I wasn't sure what you meant by "We only need to validate all the existing drivers how do they behave." - any resources you can point me towards?
Thanks

use actions for double-click

---

README.md

We're continuing to get a lot of value out of Etaoin. Keep up the good work! :100:

Update Kevel company name (formerly Adzerk)

---

test/etaoin/proc_test.clj

Fix proc-test for Windows

---

test/etaoin/api_test.clj

No longer test Safari on Windows

---

Makefile
README.adoc
project.clj

Was formerly self-publishing via codox.
Add cljdoc badge and also snuck in badges for:
- slack
- clojars
Closes #389

Move to cljdoc for docs

---

CHANGELOG.adoc
test/etaoin/api_test.clj

Look for safaridrver on PATH by default

---

.gitignore

Update .gitignore [skip ci]

---

CHANGELOG.adoc
README.adoc

Minor edits.
Mention Microsoft Edge.
No need for Release Notes section now that we have a change log.

Readme tweaks [skip ci]

---

.github/CODEOWNERS

Add CODEOWNERS file [skip ci]

---

Makefile

It is no longer needed
Addendum to #389

maint: turf old markdown toc build support

---

project.clj
src/etaoin/api.clj

road to bb: Use JDK Base64 decoding support

---

doc/01-user-guide.adoc

Reviewed and updated start of user guide and ensured first getting
started examples still run today.
Will do more verification of rest of doc (it is big!) bit by bit in the
future.
Closes #380

road to bb: docs added to user guide [skip ci]

---

env/test/resources/html/test.html
src/etaoin/api.clj
test/etaoin/api_test.clj

This hopefully fixes #444.
---
Unfortunately, I wasn't able to run the tests due to a variety of technical issues.
I don't have Docker on this machine, so I attempted running `bb test all` directly.
I got an error about the Cognitect test runner library missing `:sha` from the coordinate, which I've read can be caused by using an older version of the Clojure CLI. But then I updated to the latest Clojure CLI version and the problem persisted. I was able to work around that by adding an additional `:sha` entry for all deps that have a `:git/sha` entry.
Having worked that out, I ran `bb test all` and got this error which I don't understand:
```
$ bb test all
[ TASK test all ]----------------------------------------------------------------
[ Running all tests on jvm …
```

Pragmatic displayed impl

---

CHANGELOG.adoc
doc/01-user-guide.adoc
src/etaoin/api.clj

Automatically create parent dirs for screenshots

---

CHANGELOG.adoc
deps.edn
doc/01-user-guide.adoc
src/etaoin/api.clj
src/etaoin/impl/proc.clj

Of note: now using babashka.process.
Closes #466

Allow WebDriver process output to flow to console

---

.github/workflows/test.yml

A stab at addressing timeouts on Windows CI

---

doc/01-user-guide.adoc

Add a couple more troubleshooting scenarios

docs: user-guide: troubleshooting

---

.github/workflows/test.yml

ci: ubuntu: adapt: install x11 utils

---

README.adoc

Now pointing to actual short story that inspired the name of this project.
Closes #479

docs: README: adjust link to Etaoin Shrdlu

---

README.adoc

docs: README: add real world usages [skip ci]

---

doc/01-user-guide.adoc

They are not Clojure based, but are worth mentioning.
Closes #478

docs: list other popular alternatives to Etaoin

---

.github/workflows/test.yml

Still seeing sporadic read timeouts on GitHub Actions macos test runs.
Let's try: https://github.com/actions/virtual-environments/issues/1187#issuecomment-696195756
Addendum to #464

ci: try adjusting macos network settings

---

CHANGELOG.adoc
bb.edn
deps.edn
test/etaoin/api_test.clj

maint: bump deps

---

CHANGELOG.adoc
src/etaoin/impl/proc.cljc

Fix rendering of exceptions when used from REPL

---

.github/workflows/test.yml
CHANGELOG.adoc
src/etaoin/api.clj

Fix #524: reflection for both bb and jvm

---

doc/01-user-guide.adoc
script/test_matrix.clj

ci: disable failing test-doc test

---

doc/01-user-guide.adoc

docs: user guide: add note on bb and timbre

---

CHANGELOG.adoc
Dockerfile
bb.edn
deps.edn
doc/01-user-guide.adoc
doc/02-developer-guide.adoc
script/docker_entry.clj
script/docker_install.clj
script/helper/os.clj
script/helper/virtual_display.clj
script/test.clj
script/test_doc.clj
script/test_matrix.clj

docs: user guide examples now os agnostic

---

doc/01-user-guide.adoc

Also add blurbs to existing interesting alternatives listed in user guide.
Closes #535

docs: add Wally as an alternative [skip ci]

---

deps.edn

maint: bump internal test/lint deps

---

doc/01-user-guide.adoc

test-doc: adapt to wikipedia sporadic querystring

---

deps.edn

test & ci: bump test-doc-blocks

---

bb.edn
build/build_shared.clj
deps.edn
doc/02-developer-guide.adoc

tests: don't throw in test result summary

---

bb.edn

dev: docker-run now returns exit code of command

---

.gitignore

dev: have git ignore .vscode dir [skip ci]

---

doc/01-user-guide.adoc

For maintainability. Should also adapt better to smaller screens. Each option is now also linkable and shows up in the table of contents.
Also made minor updates/corrections/clarifications.
Closes #594

docs: user guide: restructure driver options

---

bb.edn
deps.edn

dev: maint: bump internal deps

---

CHANGELOG.adoc
README.adoc

doc: thank Dave Roberts for contribution [skip ci]

---

.gitignore

Trivial addition of "*~" to .gitignore.

Ignore emacs backup files

---

CHANGELOG.adoc

- use adoc attributes for github links
- add dates and anchors to release titles (upcoming #529 will do this automatically for new releases)
- honor folks who made the changes
[skip ci]

docs: review & update changelog

---

.github/ISSUE_TEMPLATE/bug_report.md
doc/01-user-guide.adoc

docs: typos [skip ci]

---

test/etaoin/api_test.clj
test/etaoin/api_with_driver_test.clj
test/etaoin/ide_test.clj
test/etaoin/test_report.clj

This should help especially with test-doc, but seems like a good thing to report in general.
Closes #628

dev: include test context when running tests

---

test/etaoin/api_test.clj

Since this test is not really user-visible, I have not updated CHANGELOG.
Closes issue #636.

Add test for fill-active

---

CHANGELOG.adoc
src/etaoin/api.clj
test/etaoin/api_test.clj

Fix logic bug in `intersects?`

---

src/etaoin/api.clj

Improve fill-multi/fill-human-multi errors

---

README.adoc
doc/01-user-guide.adoc

Thanks for the great blog post @abogoyavlensky!

docs: link to post on testing with testcontainers

---

README.adoc

New target describes babashka badges
See https://github.com/babashka/babashka/issues/1798
[skip ci]

docs: readme: update babashka badge target

---

deps.edn

dev & test: bump deps
